name: Deploy when we change app python script
on:
  push:
    branch:
      - main
    paths:
      - "app/**"
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    steps:
      - name: "hello world"
        run: echo "Hello World"