name: Deploy Python Lambda

on:
  push:
    branches:
      - main


jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout the project"
        uses: actions/checkout@v3
      - name: "Configure AWS Credentials Action For GitHub Actions"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: "Setup Terraform CLI"
        uses: hashicorp/setup-terraform@v2.0.3

      - name: "What in the dir"
        run: find .

      - name: "Terraform format - (check if terraform config is proper formatted)"
        working-directory: ./infra
        id: fmt
        run: terraform fmt -check
      - name: "Terraform init"
        working-directory: ./infra
        id: init
        run: terraform init
      - name: "Terraform Validate"
        working-directory: ./infra
        id: validate
        run: terraform validate -no-color
      - name: "Terraform plan"
        working-directory: ./infra
        id: plan
        run: terraform plan
      - name: "Terraform apply"
        working-directory: ./infra
        id: apply
        run: terraform apply -auto-approve


jobs:
  deploy



        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
